global using NLog.Extensions.Logging;
global using Quartz;
global using Microsoft.AspNetCore.Hosting;
global using MediatR;
global using LogLevel = Microsoft.Extensions.Logging.LogLevel;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using System.Reflection;
global using WebRequest.Application.Configuration;
global using WebRequest.JobExecution;
global using WebRequest.Extensions;
global using WebRequest.Common;
global using WebRequest.Domain.Interfaces;